
GET http://localhost:5000/

###

GET http://localhost:5000/users


###

POST http://localhost:5000/users
Content-Type: application/json

{
    "firstName": "Anton",
    "lastName": "Mäenpää",
    "age": 29
}
###

GET http://localhost:5000/users/82538

###

DELETE http://localhost:5000/users/75587

###

PUT http://localhost:5000/users/287102
Content-Type: application/json

{
    "firstName": "Anton",
    "lastName": "Mäenpää",
    "age": 29
}
